[package]
name = "varfish-server-worker"
version = "0.10.2"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Rust-based worker for varfish-server"
license = "MIT"
homepage = "https://github.com/bihealth/varfish-server-worker"
edition = "2021"
readme = "README.md"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
annonars = "0.24"
anyhow = { version = "1.0", features = ["backtrace"] }
base16ct = "0.2"
bio = "1.4"
byteorder = { version = "1.5", features = ["i128"] }
bytesize = "1.3"
byte-unit = "4.0"
chrono = { version = "0.4", features = ["serde"] }
clap-verbosity-flag = "2.0"
clap = { version = "4.4", features = ["derive", "help"] }
console = "0.15"
csv = "1.1"
derive_builder = { version = "0.12", features = ["clippy"] }
derive-new = "0.5.9"
enum-map = { version = "2.6", features = ["serde"] }
ext-sort = { version = "0.1", features = ["memory-limit", "bytesize"] }
fastrand = "2.0"
flate2 = "1.0"
hgvs = "0.11"
indexmap = { version = "2.0", features = ["serde"] }
itertools = "0.11"
log = "0.4"
mehari = "0.14"
multimap = "0.9"
noodles-bgzf = { version = "0.25", features = ["async"] }
noodles-vcf = { version = "0.41", features = ["async"] }
procfs = "0.15"
prost = "0.12"
rand = "0.8"
rand_core = "0.6"
rayon = "1.8"
regex = "1.10"
rocksdb-utils-lookup = "0.3"
rocksdb = { version = "0.21", features = ["multi-threaded-cf"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["serde_derive"] }
serde_with = { version = "3.3", features = ["indexmap_2"] }
shellexpand = "3.0"
strum_macros = "0.25"
strum = { version = "0.25", features = ["derive"] }
tempdir = "0.3"
thiserror = "1.0"
thousands = "0.2"
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.4", features = ["v4", "fast-rng", "serde"] }
async-compression = { version = "0.4", features = ["tokio", "gzip"] }

[build-dependencies]
prost-build = "0.12"

[dev-dependencies]
async-std = { version = "1.12", features = ["attributes"] }
file_diff = "1.0"
float-cmp = "0.9"
hxdmp = "0.2.1"
insta = { version = "1.34", features = ["yaml"] }
pretty_assertions = "1.4"
rstest = "0.18.2"
serde_test = "1.0"
temp_testdir = "0.2"
tracing-test = "0.2"

[[bin]]
name = "varfish-server-worker"
path = "src/main.rs"
